[package]
name = "img2ascii_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = {version = "0.65"}
image = "0.24.2"
imageproc = "0.23.0"
rusttype = "0.9.2"